service: why-waste-backend
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  restaurants:
    handler: handler.app
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: /restaurant/{PostCode}
          method: get
          cors: true # Cross Origin Resource Sharing
      - http:
          path: /meal
          method: post
          cors: true # Cross Origin Resource Sharing
      - http:
          path: /restaurant
          method: post
          cors: true # Cross Origin Resource Sharing
      - http:
          path: /meal
          method: delete
          cors: true # Cross Origin Resource Sharing
      - http:
          path: /restaurant
          method: delete
          cors: true # Cross Origin Resource Sharing
      - http:
          path: /meal
          method: put
          cors: true # Cross Origin Resource Sharing